# Generated by Django 6.0.6 on 2026-07-13 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('daily', '매일'), ('weekly', '매주'), ('monthly', '매월')], default='daily', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '체크리스트 항목',
                'verbose_name_plural': '체크리스트 항목',
                'ordering': ['title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_assignments', to='core.department')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_assignments', to='checklist.checklistitem')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '부서 체크리스트 배정',
                'verbose_name_plural': '부서 체크리스트 배정',
                'ordering': ['department_id', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField()),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
                ('department_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='checklist.departmentchecklistitem')),
            ],
            options={
                'verbose_name': '체크리스트 완료 기록',
                'verbose_name_plural': '체크리스트 완료 기록',
                'ordering': ['-date', 'department_item_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='departmentchecklistitem',
            constraint=models.UniqueConstraint(fields=('item', 'department'), name='checklist_unique_item_department'),
        ),
        migrations.AddConstraint(
            model_name='checklistrecord',
            constraint=models.UniqueConstraint(fields=('department_item', 'date'), name='checklist_unique_department_item_date'),
        ),
    ]
