# Generated by Django 6.0.6 on 2026-07-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='timing',
            field=models.CharField(choices=[('opening', '오픈'), ('specific', '특정 시점'), ('closing', '마감')], default='specific', max_length=20),
        ),
    ]
