# Generated by Django 6.0.6 on 2026-06-17 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('BEAUTY_SUPPLY', '미용소모품'), ('MEDICAL_SUPPLY', '의료용품'), ('HYGIENE_SUPPLY', '위생용품'), ('MEDICINE', '의약품'), ('GENERAL_SUPPLY', '일반소모품'), ('DEDICATED_SUPPLY', '전용소모품'), ('OTHER', '기타')], max_length=30)),
                ('specification', models.CharField(blank=True, default='', max_length=150)),
                ('memo', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '품목',
                'verbose_name_plural': '품목',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('homepage', models.URLField(blank=True, default='', max_length=255)),
                ('manager_name', models.CharField(blank=True, default='', max_length=100)),
                ('manager_phone', models.CharField(blank=True, default='', max_length=50)),
                ('memo', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '공급업체',
                'verbose_name_plural': '공급업체',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManagedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('EA', 'EA'), ('BOX', 'BOX'), ('PACK', 'PACK'), ('P', 'P'), ('ROLL', 'ROLL'), ('BOTTLE', 'BOTTLE'), ('VIAL', 'VIAL'), ('AMP', 'AMP'), ('ML', 'ML'), ('G', 'G'), ('KG', 'KG'), ('SET', 'SET'), ('OTHER', 'OTHER')], default='EA', max_length=20)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('storage_location', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('memo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_items', to='core.department')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_items', to='inventory.item')),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_items', to='inventory.supplier')),
            ],
            options={
                'verbose_name': '관리품목',
                'verbose_name_plural': '관리품목',
                'ordering': ['department', 'item'],
                'constraints': [models.UniqueConstraint(fields=('department', 'item'), name='uniq_managed_item_department_item')],
            },
        ),
    ]
