# Generated by Django 6.0.6 on 2026-06-17 00:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INITIAL_COUNT', '초기재고'), ('IN', '입고'), ('OUT_USE', '사용'), ('OUT_DISCARD', '폐기'), ('OUT_LOST', '분실'), ('OUT_GIFT', '증정'), ('OUT_OTHER', '기타출고'), ('ADJUSTMENT', '실사조정')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('APPROVED', '승인'), ('REJECTED', '반려'), ('CANCELED', '취소')], default='PENDING', max_length=20)),
                ('quantity_input', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantity_delta', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('expected_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('review_note', models.TextField(blank=True, default='')),
                ('memo', models.TextField(blank=True, default='')),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('canceled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canceled_stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('managed_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.manageditem')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.supplier')),
            ],
            options={
                'verbose_name': '재고 거래',
                'verbose_name_plural': '재고 거래',
                'ordering': ['-occurred_at', '-created_at', '-id'],
                'indexes': [models.Index(fields=['managed_item', 'status'], name='idx_stock_tx_mi_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'APPROVED'), ('transaction_type', 'INITIAL_COUNT')), fields=('managed_item',), name='uniq_approved_initial_count_per_managed_item'), models.CheckConstraint(condition=models.Q(('quantity_input__gte', 0)), name='ck_stock_tx_quantity_input_gte_0'), models.CheckConstraint(condition=models.Q(('expected_quantity__gte', 0), ('expected_quantity__isnull', True), _connector='OR'), name='ck_stock_tx_expected_quantity_gte_0_or_null'), models.CheckConstraint(condition=models.Q(('actual_quantity__gte', 0), ('actual_quantity__isnull', True), _connector='OR'), name='ck_stock_tx_actual_quantity_gte_0_or_null'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0), ('unit_price__isnull', True), _connector='OR'), name='ck_stock_tx_unit_price_gte_0_or_null')],
            },
        ),
    ]
