# Generated by Django 6.0.6 on 2026-07-01 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stocktransaction_transaction_type_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='source_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.orderitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', '주문완료'), ('PARTIALLY_RECEIVED', '부분입고'), ('RECEIVED', '입고완료'), ('CANCELED', '취소')], default='ORDERED', max_length=20),
        ),
    ]
