# Generated by Django 6.0.6 on 2026-07-04 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stocktransaction_source_order_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='remaining_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='remaining_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_order_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='remaining_closed_memo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='remaining_closed_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='remaining_closed_reason',
            field=models.CharField(blank=True, choices=[('SOLD_OUT', '품절'), ('REFUND', '환불'), ('REORDER_OTHER', '타업체 재주문'), ('ORDER_CANCELED', '주문 취소'), ('GIVE_UP', '입고 포기'), ('OTHER', '기타')], default='', max_length=20),
        ),
    ]
