# Generated by Django 6.0.6 on 2026-07-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_orderitem_remaining_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('EA', 'EA'), ('BOX', 'BOX'), ('PACK', 'PACK'), ('P', 'P'), ('ROLL', 'ROLL'), ('BOTTLE', 'BOTTLE'), ('VIAL', 'VIAL'), ('AMP', 'AMP'), ('ML', 'ML'), ('G', 'G'), ('KG', 'KG'), ('SET', 'SET'), ('OTHER', 'OTHER')], max_length=20, null=True, verbose_name='주문단위'),
        ),
    ]
