# Generated by Django 6.0.6 on 2026-07-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_copy_unit_manageditem_to_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageditem',
            name='unit',
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(choices=[('EA', 'EA'), ('BOX', 'BOX'), ('PACK', 'PACK'), ('P', 'P'), ('ROLL', 'ROLL'), ('BOTTLE', 'BOTTLE'), ('VIAL', 'VIAL'), ('AMP', 'AMP'), ('ML', 'ML'), ('G', 'G'), ('KG', 'KG'), ('SET', 'SET'), ('OTHER', 'OTHER')], max_length=20, verbose_name='주문단위'),
        ),
    ]
