# Generated by Django 6.0.6 on 2026-07-11 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target_type', models.CharField(choices=[('all', '전체'), ('department', '부서')], default='all', max_length=20)),
                ('status', models.CharField(choices=[('draft', '임시저장'), ('published', '게시')], default='draft', max_length=20)),
                ('is_important', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('general', '일반'), ('operation', '운영'), ('education', '교육'), ('admin', '행정')], default='general', max_length=20)),
                ('reference_url', models.URLField(blank=True, default='')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notices', to='core.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '공지',
                'verbose_name_plural': '공지',
                'ordering': ['-created_at'],
            },
        ),
    ]
